CREATE TABLE KHOA (
    MAKHOA CHAR(6) PRIMARY KEY,
    TENKHOA NVARCHAR2(30) NOT NULL,
    SDT CHAR(10),
    TRUONGKHOA INT 
);


CREATE TABLE BENHNHAN (
    MABN INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TENBN NVARCHAR2(100) NOT NULL,
    PHAI NVARCHAR2(3),
    NGAYSINH DATE,
    CCCD CHAR(12) UNIQUE,
    SONHA NVARCHAR2(5),
    TENDUONG NVARCHAR2(30),
    QUANHUYEN NVARCHAR2(30),
    TINHTP NVARCHAR2(50),
    TIENSUBENH NVARCHAR2(2000),
    TIENSUBENHGD NVARCHAR2(2000),
    DIUNGTHUOC NVARCHAR2(2000),
    USERNAME VARCHAR2(50),
    CONSTRAINT CK_BN_PHAI CHECK (PHAI IN ('Nam', 'Nữ'))
);

CREATE TABLE NHANVIEN (
    MANV INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    HOTEN NVARCHAR2(100) NOT NULL,
    PHAI NVARCHAR2(3),
    NGAYSINH DATE,
    CMND CHAR(12) UNIQUE,
    QUEQUAN NVARCHAR2(100),
    SODT CHAR(10),
    VAITRO NVARCHAR2(50),
    CHUYENKHOA CHAR(6),
    USERNAME VARCHAR2(50),

    CONSTRAINT FK_NV_KHOA FOREIGN KEY (CHUYENKHOA) REFERENCES KHOA(MAKHOA),
    CONSTRAINT CK_NV_PHAI CHECK (PHAI IN ('Nam', 'Nữ'))
);

CREATE TABLE HSBA (
    MAHSBA INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MABN INT,
    NGAY DATE,
    CHANDOAN NVARCHAR2(2000),
    DIEUTRI NVARCHAR2(2000),
    KETLUAN NVARCHAR2(2000),
    MABS INT,
    MAKHOA CHAR(6),

    CONSTRAINT FK_HSBA_BN
        FOREIGN KEY (MABN)
        REFERENCES BENHNHAN(MABN),

    CONSTRAINT FK_HSBA_BS
        FOREIGN KEY (MABS)
        REFERENCES NHANVIEN(MANV),

    CONSTRAINT FK_HSBA_KHOA
        FOREIGN KEY (MAKHOA)
        REFERENCES KHOA(MAKHOA)
);

CREATE TABLE HSBA_DV (
    MAHSBA INT,
    LOAIDV NVARCHAR2(20),
    NGAYDV DATE,
    KETQUA NVARCHAR2(2000),
    MAKTV INT,

    CONSTRAINT PK_HSBA_DV
        PRIMARY KEY (MAHSBA, LOAIDV, NGAYDV),

    CONSTRAINT FK_DV_HSBA
        FOREIGN KEY (MAHSBA)
        REFERENCES HSBA(MAHSBA),

    CONSTRAINT FK_DV_KTV
        FOREIGN KEY (MAKTV)
        REFERENCES NHANVIEN(MANV)
);


CREATE TABLE DONTHUOC (
    MAHSBA INT,
    TENTHUOC NVARCHAR2(100),
    LIEUDUNG NVARCHAR2(200),
    NGAYDT DATE,

    CONSTRAINT PK_DONTHUOC
        PRIMARY KEY (MAHSBA, TENTHUOC, NGAYDT),

    CONSTRAINT FK_DT_HSBA
        FOREIGN KEY (MAHSBA)
        REFERENCES HSBA(MAHSBA)
);

CREATE TABLE THONGBAO (
    MATHONGBAO INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOIDUNG NVARCHAR2(2000),
    NGAYGIO TIMESTAMP,
    DIADIEM NVARCHAR2(100)
);

