/* ================================================= */
/* 1. CLEANUP (Drop existing tables to avoid errors) */
/* ================================================= */
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE HSBA_DV CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DONTHUOC CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE HSBA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE NHANVIEN CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE KHOA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE BENHNHAN CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE THONGBAO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

/* ================================================= */
/* 2. CREATE TABLES (In Specific Order)              */
/* ================================================= */

-- 1. Create BENHNHAN (No dependencies)
CREATE TABLE BENHNHAN (
    MABN VARCHAR2(32) DEFAULT LOWER(RAWTOHEX(SYS_GUID())) PRIMARY KEY,
    TENBN NVARCHAR2(100) NOT NULL,
    PHAI NVARCHAR2(3),
    NGAYSINH DATE,
    CCCD CHAR(12) UNIQUE NOT NULL,
    SONHA NVARCHAR2(30),
    TENDUONG NVARCHAR2(30),
    QUANHUYEN NVARCHAR2(30),
    TINHTP NVARCHAR2(50),
    TIENSUBENH NVARCHAR2(2000),
    TIENSUBENHGD NVARCHAR2(2000),
    DIUNGTHUOC NVARCHAR2(2000),
    USERNAME VARCHAR2(30) NOT NULL,
    PASSWORD_HASH VARCHAR2(100),
    CONSTRAINT CK_BN_PHAI CHECK (PHAI IN (N'Nam', N'Nữ')),
    CONSTRAINT CK_BN_USERNAME_CCCD CHECK (USERNAME = CCCD),
    CONSTRAINT CK_BN_NGAYSINH_DATEONLY CHECK (NGAYSINH IS NULL OR NGAYSINH = TRUNC(NGAYSINH))
);

-- 2. Create KHOA (REMOVED foreign key to NHANVIEN for now)
CREATE TABLE KHOA (
    MAKHOA CHAR(6) PRIMARY KEY,
    TENKHOA NVARCHAR2(30) NOT NULL,
    SDT CHAR(10),
    TRUONGKHOA VARCHAR2(32)
);

-- 3. Create NHANVIEN (Now safe to reference KHOA)
CREATE TABLE NHANVIEN (
    MANV VARCHAR2(32) DEFAULT LOWER(RAWTOHEX(SYS_GUID())) PRIMARY KEY,
    HOTEN NVARCHAR2(100) NOT NULL,
    PHAI NVARCHAR2(3),
    NGAYSINH DATE,
    CCCD CHAR(12) UNIQUE NOT NULL,
    QUEQUAN NVARCHAR2(100),
    SODT CHAR(10),
    VAITRO NVARCHAR2(50),
    CHUYENKHOA CHAR(6),
    USERNAME VARCHAR2(30) NOT NULL,
    PASSWORD_HASH VARCHAR2(100),

    CONSTRAINT FK_NV_KHOA FOREIGN KEY (CHUYENKHOA) REFERENCES KHOA(MAKHOA),
    CONSTRAINT CK_NV_PHAI CHECK (PHAI IN (N'Nam', N'Nữ')),
    CONSTRAINT CK_NV_VAITRO CHECK (VAITRO IN (N'Điều phối viên', N'Bác sĩ/Y sĩ', N'Kỹ thuật viên', N'Bệnh nhân')),
    CONSTRAINT CK_NV_USERNAME_CCCD CHECK (USERNAME = CCCD),
    CONSTRAINT CK_NV_NGAYSINH_DATEONLY CHECK (NGAYSINH IS NULL OR NGAYSINH = TRUNC(NGAYSINH))
);

-- 4. NOW add the circular Foreign Key back to KHOA
ALTER TABLE KHOA 
ADD CONSTRAINT FK_KHOA_TRUONGKHOA 
FOREIGN KEY (TRUONGKHOA) REFERENCES NHANVIEN(MANV);

-- 5. Create HSBA (References BENHNHAN, NHANVIEN, KHOA - all exist now)
CREATE TABLE HSBA (
    MAHSBA INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MABN VARCHAR2(32),
    NGAY DATE,
    CHANDOAN NVARCHAR2(2000),
    DIEUTRI NVARCHAR2(2000),
    KETLUAN NVARCHAR2(2000),
    MABS VARCHAR2(32),
    MAKHOA CHAR(6),

    CONSTRAINT FK_HSBA_BN FOREIGN KEY (MABN) REFERENCES BENHNHAN(MABN),
    CONSTRAINT FK_HSBA_BS FOREIGN KEY (MABS) REFERENCES NHANVIEN(MANV),
    CONSTRAINT FK_HSBA_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
);

-- 6. Create HSBA_DV
CREATE TABLE HSBA_DV (
    MAHSBA INT,
    LOAIDV NVARCHAR2(100),
    NGAYDV DATE,
    KETQUA NVARCHAR2(2000),
    MAKTV VARCHAR2(32),

    CONSTRAINT PK_HSBA_DV PRIMARY KEY (MAHSBA, LOAIDV, NGAYDV),
    CONSTRAINT FK_DV_HSBA FOREIGN KEY (MAHSBA) REFERENCES HSBA(MAHSBA),
    CONSTRAINT FK_DV_KTV FOREIGN KEY (MAKTV) REFERENCES NHANVIEN(MANV)
);

-- 7. Create DONTHUOC
CREATE TABLE DONTHUOC (
    MAHSBA INT,
    TENTHUOC NVARCHAR2(100),
    LIEUDUNG NVARCHAR2(200),
    NGAYDT DATE,

    CONSTRAINT PK_DONTHUOC PRIMARY KEY (MAHSBA, TENTHUOC, NGAYDT),
    CONSTRAINT FK_DT_HSBA FOREIGN KEY (MAHSBA) REFERENCES HSBA(MAHSBA)
);

-- 8. Create THONGBAO
CREATE TABLE THONGBAO (
    MATHONGBAO INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOIDUNG NVARCHAR2(2000),
    NGAYGIO TIMESTAMP,
    DIADIEM NVARCHAR2(100)
);