BEGIN EXECUTE IMMEDIATE 'DROP INDEX IDX_HSBA_MABN'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1418 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP INDEX IDX_HSBA_MABS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1418 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP INDEX IDX_HSBADV_LOAIDV'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1418 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP INDEX IDX_HSBADV_NGAYDV'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1418 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP INDEX IDX_THONGBAO_NOIDUNG'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1418 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP INDEX IDX_THONGBAO_DIADIEM'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1418 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP INDEX IDX_DONTHUOC_TENTHUOC'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1418 THEN RAISE; END IF; END;
/

/* Patient records query */
CREATE INDEX IDX_HSBA_MABN
ON HSBA (MABN);

/* Doctor workload query */
CREATE INDEX IDX_HSBA_MABS
ON HSBA (MABS);


/* =========================
   HSBA_DV
   ========================= */

/* Service lookup by type */
CREATE INDEX IDX_HSBADV_LOAIDV
ON HSBA_DV (LOAIDV);

/* Service lookup by date */
CREATE INDEX IDX_HSBADV_NGAYDV
ON HSBA_DV (NGAYDV);


/* =========================
   THONGBAO
   ========================= */

/* OLS filtering - composite index */
CREATE INDEX IDX_THONGBAO_NOIDUNG
ON THONGBAO (NOIDUNG);


CREATE INDEX IDX_THONGBAO_DIADIEM
ON THONGBAO (DIADIEM);
 
/* =========================
   DONTHUOC
   ========================= */

/* Lookup by drug name */
CREATE INDEX IDX_DONTHUOC_TENTHUOC
ON DONTHUOC (TENTHUOC);

