SET LINESIZE 300;
SET PAGESIZE 100;

COL USERNAME FORMAT A15;
COL DB_USER FORMAT A15;
COL USERHOST FORMAT A15;
COL TERMINAL FORMAT A15;
COL OBJECT_NAME FORMAT A15;
COL OBJ_NAME FORMAT A15;
COL ACTION_NAME FORMAT A20;
COL POLICY_NAME FORMAT A25;
COL STATEMENT_TYPE FORMAT A15;
COL SQL_TEXT FORMAT A70;

PROMPT === Session audit trail (login/logout - success only) ===
SELECT USERNAME,
       USERHOST,
       TERMINAL,
       RETURNCODE,
       TO_CHAR(TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS') AS LOGON_TIME,
       TO_CHAR(LOGOFF_TIME, 'YYYY-MM-DD HH24:MI:SS') AS LOGOFF_TIME,
       SESSIONID
FROM DBA_AUDIT_SESSION
WHERE RETURNCODE = 0
ORDER BY TIMESTAMP DESC;

PROMPT === Standard audit trail ===
SELECT USERNAME,
       ACTION_NAME,
       OBJ_NAME,
       RETURNCODE,
    TO_CHAR(EXTENDED_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS') AS ACTION_TIME
FROM DBA_AUDIT_TRAIL
WHERE OBJ_NAME IN ('BENHNHAN', 'HSBA', 'HSBA_DV', 'DONTHUOC')
ORDER BY EXTENDED_TIMESTAMP DESC;

PROMPT === FGA trail ===
SELECT DB_USER,
       OBJECT_SCHEMA,
       OBJECT_NAME,
       POLICY_NAME,
       STATEMENT_TYPE,
       TO_CHAR(TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS') AS ACTION_TIME,
       SQL_TEXT
FROM DBA_FGA_AUDIT_TRAIL
WHERE OBJECT_NAME IN ('HSBA', 'HSBA_DV', 'DONTHUOC')
ORDER BY TIMESTAMP DESC;

PROMPT === DONTHUOC audit scenario ===
SELECT DB_USER,
       OBJECT_NAME,
       POLICY_NAME,
       STATEMENT_TYPE,
       TO_CHAR(TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS') AS ACTION_TIME,
       SQL_TEXT
FROM DBA_FGA_AUDIT_TRAIL
WHERE OBJECT_NAME = 'DONTHUOC'
ORDER BY TIMESTAMP DESC;

PROMPT === HSBA audit scenarios ===
SELECT DB_USER,
       OBJECT_NAME,
       POLICY_NAME,
       STATEMENT_TYPE,
       TO_CHAR(TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS') AS ACTION_TIME,
       SQL_TEXT
FROM DBA_FGA_AUDIT_TRAIL
WHERE OBJECT_NAME = 'HSBA'
ORDER BY TIMESTAMP DESC;

PROMPT === HSBA_DV illegal DML scenario ===
SELECT DB_USER,
       OBJECT_NAME,
       POLICY_NAME,
       STATEMENT_TYPE,
       TO_CHAR(TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS') AS ACTION_TIME,
       SQL_TEXT
FROM DBA_FGA_AUDIT_TRAIL
WHERE OBJECT_NAME = 'HSBA_DV'
ORDER BY TIMESTAMP DESC;
