SET SERVEROUTPUT ON;

PROMPT === Bootstrap HOSPITAL_ADMIN ===

DECLARE
    v_con_name VARCHAR2(128);
    v_exists   NUMBER := 0;
BEGIN
    SELECT SYS_CONTEXT('USERENV', 'CON_NAME')
    INTO v_con_name
    FROM dual;

    DBMS_OUTPUT.PUT_LINE('Current container: ' || v_con_name);

    IF v_con_name = 'CDB$ROOT' THEN
        RAISE_APPLICATION_ERROR(
            -20001,
            'Do not create HOSPITAL_ADMIN in CDB$ROOT. Connect to the project PDB first, for example XEPDB1.'
        );
    END IF;

    SELECT COUNT(*)
    INTO v_exists
    FROM DBA_USERS
    WHERE USERNAME = 'HOSPITAL_ADMIN';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER HOSPITAL_ADMIN IDENTIFIED BY "12345678"';
        DBMS_OUTPUT.PUT_LINE('Created user HOSPITAL_ADMIN.');
    ELSE
        EXECUTE IMMEDIATE 'ALTER USER HOSPITAL_ADMIN IDENTIFIED BY "12345678" ACCOUNT UNLOCK';
        DBMS_OUTPUT.PUT_LINE('Updated password and unlocked HOSPITAL_ADMIN.');
    END IF;
END;
/

GRANT CREATE SESSION TO HOSPITAL_ADMIN;
GRANT CONNECT TO HOSPITAL_ADMIN;
GRANT RESOURCE TO HOSPITAL_ADMIN;
GRANT CREATE ROLE TO HOSPITAL_ADMIN;
GRANT CREATE USER TO HOSPITAL_ADMIN;
GRANT ALTER USER TO HOSPITAL_ADMIN;
GRANT DROP USER TO HOSPITAL_ADMIN;
GRANT CREATE TABLE TO HOSPITAL_ADMIN;
GRANT CREATE VIEW TO HOSPITAL_ADMIN;
GRANT CREATE PROCEDURE TO HOSPITAL_ADMIN;
GRANT CREATE SEQUENCE TO HOSPITAL_ADMIN;
GRANT CREATE TRIGGER TO HOSPITAL_ADMIN;
GRANT CREATE TYPE TO HOSPITAL_ADMIN;
GRANT CREATE SYNONYM TO HOSPITAL_ADMIN;
GRANT UNLIMITED TABLESPACE TO HOSPITAL_ADMIN;

GRANT AUDIT SYSTEM TO HOSPITAL_ADMIN;
GRANT SELECT_CATALOG_ROLE TO HOSPITAL_ADMIN;
GRANT GRANT ANY ROLE TO HOSPITAL_ADMIN;
GRANT GRANT ANY PRIVILEGE TO HOSPITAL_ADMIN;
GRANT EXECUTE ON DBMS_RLS TO HOSPITAL_ADMIN;
GRANT EXECUTE ON DBMS_FGA TO HOSPITAL_ADMIN;

BEGIN
    EXECUTE IMMEDIATE 'GRANT LBAC_DBA TO HOSPITAL_ADMIN';
    DBMS_OUTPUT.PUT_LINE('Granted LBAC_DBA to HOSPITAL_ADMIN.');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Could not grant LBAC_DBA: ' || SQLERRM);
END;
/

BEGIN
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON LBACSYS.SA_SYSDBA TO HOSPITAL_ADMIN';
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Could not grant LBACSYS.SA_SYSDBA: ' || SQLERRM);
END;
/

BEGIN
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON LBACSYS.SA_COMPONENTS TO HOSPITAL_ADMIN';
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Could not grant LBACSYS.SA_COMPONENTS: ' || SQLERRM);
END;
/

BEGIN
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON LBACSYS.SA_LABEL_ADMIN TO HOSPITAL_ADMIN';
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Could not grant LBACSYS.SA_LABEL_ADMIN: ' || SQLERRM);
END;
/

BEGIN
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON LBACSYS.LBAC_POLICY_ADMIN TO HOSPITAL_ADMIN';
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Could not grant LBACSYS.LBAC_POLICY_ADMIN: ' || SQLERRM);
END;
/

BEGIN
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON LBACSYS.SA_USER_ADMIN TO HOSPITAL_ADMIN';
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Could not grant LBACSYS.SA_USER_ADMIN: ' || SQLERRM);
END;
/

PROMPT === HOSPITAL_ADMIN bootstrap completed ===
