SET SERVEROUTPUT ON;
BEGIN
    EXECUTE IMMEDIATE 'ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE';
    DBMS_OUTPUT.PUT_LINE('Enabled _ORACLE_SCRIPT for this session.');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipping _ORACLE_SCRIPT change: ' || SQLERRM);
END;
/

PROMPT === STARTING FULL SYSTEM RESET ===

PROMPT [1/9] Dropping FGA policies...
BEGIN
    DBMS_FGA.DROP_POLICY(USER, 'DONTHUOC', 'FGA_DONTHUOC_AFTER_CREATE');
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    DBMS_FGA.DROP_POLICY(USER, 'HSBA', 'FGA_HSBA_VALID_UPDATE');
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    DBMS_FGA.DROP_POLICY(USER, 'HSBA', 'FGA_HSBA_INVALID_UPDATE');
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    DBMS_FGA.DROP_POLICY(USER, 'HSBA_DV', 'FGA_HSBA_DV_ILLEGAL_DML');
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
PROMPT [1/9] Done.

PROMPT [2/9] Removing standard audit rules...
BEGIN EXECUTE IMMEDIATE 'NOAUDIT SESSION'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'NOAUDIT SELECT ON BENHNHAN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'NOAUDIT INSERT, UPDATE, DELETE ON HSBA_DV'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'NOAUDIT UPDATE ON HSBA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'NOAUDIT INSERT, UPDATE, DELETE ON DONTHUOC'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'NOAUDIT EXECUTE ON VPD_HSBA_FN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
PROMPT [2/9] Done.

PROMPT [3/9] Dropping VPD policies...
BEGIN DBMS_RLS.DROP_POLICY(USER, 'HSBA', 'HSBA_VPD'); EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN DBMS_RLS.DROP_POLICY(USER, 'BENHNHAN', 'BENHNHAN_VPD'); EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN DBMS_RLS.DROP_POLICY(USER, 'HSBA_DV', 'HSBA_DV_VPD'); EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN DBMS_RLS.DROP_POLICY(USER, 'DONTHUOC', 'DONTHUOC_VPD'); EXCEPTION WHEN OTHERS THEN NULL; END;
/
PROMPT [3/9] Done.

PROMPT [4/9] Dropping OLS policy...
BEGIN
    SA_POLICY_ADMIN.REMOVE_TABLE_POLICY(
        policy_name => 'THONGBAO_OLS',
        schema_name => USER,
        table_name  => 'THONGBAO',
        drop_column => TRUE
    );
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    SA_POLICY_ADMIN.REMOVE_TABLE_POLICY(
        policy_name => 'HOS_OLS_POL',
        schema_name => USER,
        table_name  => 'THONGBAO',
        drop_column => TRUE
    );
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    SA_SYSDBA.DISABLE_POLICY(policy_name => 'THONGBAO_OLS');
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    SA_SYSDBA.DISABLE_POLICY(policy_name => 'HOS_OLS_POL');
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    SA_SYSDBA.DROP_POLICY(policy_name => 'THONGBAO_OLS', drop_column => TRUE);
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    SA_SYSDBA.DROP_POLICY(policy_name => 'HOS_OLS_POL', drop_column => TRUE);
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE THONGBAO DROP COLUMN OLS_LABEL';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
PROMPT [4/9] Done.

PROMPT [5/9] Dropping helper views, trigger, and functions...
BEGIN EXECUTE IMMEDIATE 'DROP VIEW V_SELF_NHANVIEN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW V_SELF_BENHNHAN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW V_TECHNICIAN_HSBA_DV'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW V_PATIENT_HSBA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW V_PATIENT_DONTHUOC'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_HSBADV_TECH_ONLY'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION APP_CURRENT_MANV'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION APP_CURRENT_ROLE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION VPD_HSBA_FN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION VPD_BENHNHAN_FN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION VPD_HSBA_DV_FN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION VPD_DONTHUOC_FN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
PROMPT [5/9] Done.

PROMPT [6/9] Dropping generated Oracle users from NHANVIEN...
DECLARE
    TYPE t_usernames IS TABLE OF VARCHAR2(30);
    v_usernames t_usernames := t_usernames();
    v_count NUMBER := 0;
BEGIN
    BEGIN
        EXECUTE IMMEDIATE
            'SELECT USERNAME FROM NHANVIEN WHERE USERNAME IS NOT NULL'
            BULK COLLECT INTO v_usernames;
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Skipped staff-user drop because NHANVIEN is unavailable.');
            RETURN;
    END;

    FOR i IN 1 .. v_usernames.COUNT LOOP
        BEGIN
            EXECUTE IMMEDIATE 'DROP USER ' || v_usernames(i) || ' CASCADE';
            v_count := v_count + 1;
        EXCEPTION
            WHEN OTHERS THEN NULL;
        END;
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('Staff users dropped: ' || v_count);
END;
/

PROMPT [6/9] Dropping generated Oracle users from BENHNHAN...
DECLARE
    TYPE t_usernames IS TABLE OF VARCHAR2(30);
    v_usernames t_usernames := t_usernames();
    v_count NUMBER := 0;
BEGIN
    BEGIN
        EXECUTE IMMEDIATE
            'SELECT USERNAME FROM BENHNHAN WHERE USERNAME IS NOT NULL'
            BULK COLLECT INTO v_usernames;
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Skipped patient-user drop because BENHNHAN is unavailable.');
            RETURN;
    END;

    FOR i IN 1 .. v_usernames.COUNT LOOP
        BEGIN
            EXECUTE IMMEDIATE 'DROP USER ' || v_usernames(i) || ' CASCADE';
            v_count := v_count + 1;
        EXCEPTION
            WHEN OTHERS THEN NULL;
        END;
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('Patient users dropped: ' || v_count);
END;
/
PROMPT [6/9] Done.

PROMPT [7/9] Dropping application roles...
DECLARE
    v_count NUMBER := 0;
BEGIN
    FOR r IN (
        SELECT ROLE
        FROM DBA_ROLES
        WHERE ROLE IN ('DIEU_PHOI_VIEN', 'BAC_SI_Y_SI', 'KY_THUAT_VIEN', 'BENH_NHAN')
    ) LOOP
        BEGIN
            EXECUTE IMMEDIATE 'DROP ROLE ' || r.ROLE;
            v_count := v_count + 1;
        EXCEPTION
            WHEN OTHERS THEN NULL;
        END;
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('Roles dropped: ' || v_count);
END;
/
PROMPT [7/9] Done.

PROMPT [8/9] Dropping user tables...
DECLARE
    v_count NUMBER := 0;
BEGIN
    FOR t IN (
        SELECT TABLE_NAME
        FROM USER_TABLES
        WHERE TABLE_NAME NOT LIKE 'BIN$%'
    ) LOOP
        BEGIN
            EXECUTE IMMEDIATE 'DROP TABLE ' || t.TABLE_NAME || ' CASCADE CONSTRAINTS PURGE';
            v_count := v_count + 1;
        EXCEPTION
            WHEN OTHERS THEN NULL;
        END;
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('Tables dropped: ' || v_count);
END;
/
PROMPT [8/9] Done.

PROMPT [9/9] Dropping remaining sequences...
DECLARE
    v_count NUMBER := 0;
BEGIN
    FOR s IN (
        SELECT SEQUENCE_NAME
        FROM USER_SEQUENCES
    ) LOOP
        BEGIN
            EXECUTE IMMEDIATE 'DROP SEQUENCE ' || s.SEQUENCE_NAME;
            v_count := v_count + 1;
        EXCEPTION
            WHEN OTHERS THEN NULL;
        END;
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('Sequences dropped: ' || v_count);
END;
/
PROMPT [9/9] Done.

COMMIT;

PROMPT === FULL SYSTEM RESET COMPLETED ===
