---
blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/dinhdaivu/CSC12001_Data-Security-in-Information-Systems/discussions
    about: Ask questions, share ideas, and get feedback
