BEGIN EXECUTE IMMEDIATE 'DROP INDEX IDX_HSBA_MABN'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1418 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP INDEX IDX_HSBA_MABS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1418 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP INDEX IDX_HSBADV_LOAIDV'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1418 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP INDEX IDX_HSBADV_NGAYDV'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1418 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP INDEX IDX_THONGBAO_NOIDUNG'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1418 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP INDEX IDX_THONGBAO_DIADIEM'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1418 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP INDEX IDX_DONTHUOC_TENTHUOC'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1418 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP INDEX IDX_BENHNHAN_USERNAME'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1418 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP INDEX IDX_BENHNHAN_CCCD'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1418 THEN RAISE; END IF; END;
/

DECLARE
   v_idx_count NUMBER := 0;
BEGIN
   SELECT COUNT(*)
   INTO v_idx_count
   FROM USER_IND_COLUMNS
   WHERE TABLE_NAME = 'BENHNHAN'
     AND COLUMN_NAME = 'CCCD';

   IF v_idx_count = 0 THEN
      EXECUTE IMMEDIATE 'CREATE INDEX IDX_BENHNHAN_CCCD ON BENHNHAN (CCCD)';
   END IF;
END;
/

CREATE INDEX IDX_BENHNHAN_USERNAME
ON BENHNHAN (USERNAME);

/* Patient records query */
CREATE INDEX IDX_HSBA_MABN
ON HSBA (MABN);

/* Doctor workload query */
CREATE INDEX IDX_HSBA_MABS
ON HSBA (MABS);


/* =========================
   HSBA_DV
   ========================= */

/* Service lookup by type */
CREATE INDEX IDX_HSBADV_LOAIDV
ON HSBA_DV (LOAIDV);

/* Service lookup by date */
CREATE INDEX IDX_HSBADV_NGAYDV
ON HSBA_DV (NGAYDV);


/* =========================
   THONGBAO
   ========================= */

/* OLS filtering - composite index */
CREATE INDEX IDX_THONGBAO_NOIDUNG
ON THONGBAO (NOIDUNG);


CREATE INDEX IDX_THONGBAO_DIADIEM
ON THONGBAO (DIADIEM);
 
/* =========================
   DONTHUOC
   ========================= */

/* Lookup by drug name */
CREATE INDEX IDX_DONTHUOC_TENTHUOC
ON DONTHUOC (TENTHUOC);

