SET LINESIZE 200;
SET PAGESIZE 100;

PROMPT === Standard audit trail ===
SELECT USERNAME,
       ACTION_NAME,
       OBJ_NAME,
       RETURNCODE,
    TO_CHAR(EXTENDED_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS') AS ACTION_TIME
FROM DBA_AUDIT_TRAIL
WHERE OBJ_NAME IN ('BENHNHAN', 'HSBA', 'HSBA_DV', 'DONTHUOC')
ORDER BY EXTENDED_TIMESTAMP DESC;

PROMPT === FGA trail ===
SELECT DB_USER,
       OBJECT_SCHEMA,
       OBJECT_NAME,
       POLICY_NAME,
       STATEMENT_TYPE,
       TO_CHAR(TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS') AS ACTION_TIME,
       SQL_TEXT
FROM DBA_FGA_AUDIT_TRAIL
WHERE OBJECT_NAME IN ('HSBA', 'HSBA_DV', 'DONTHUOC')
ORDER BY TIMESTAMP DESC;

PROMPT === DONTHUOC audit scenario ===
SELECT *
FROM DBA_FGA_AUDIT_TRAIL
WHERE OBJECT_NAME = 'DONTHUOC'
ORDER BY TIMESTAMP DESC;

PROMPT === HSBA audit scenarios ===
SELECT *
FROM DBA_FGA_AUDIT_TRAIL
WHERE OBJECT_NAME = 'HSBA'
ORDER BY TIMESTAMP DESC;

PROMPT === HSBA_DV illegal DML scenario ===
SELECT *
FROM DBA_FGA_AUDIT_TRAIL
WHERE OBJECT_NAME = 'HSBA_DV'
ORDER BY TIMESTAMP DESC;
