SET SERVEROUTPUT ON;

PROMPT === Requirement 3 / Standard audit setup ===

AUDIT SESSION;
AUDIT SELECT ON BENHNHAN BY ACCESS WHENEVER NOT SUCCESSFUL;
AUDIT INSERT, UPDATE, DELETE ON HSBA_DV BY ACCESS WHENEVER NOT SUCCESSFUL;
AUDIT INSERT, UPDATE, DELETE ON HSBA BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON DONTHUOC BY ACCESS;
AUDIT EXECUTE ON VPD_HSBA_FN BY ACCESS;

PROMPT Five baseline contexts enabled:
PROMPT 1. Session logon/logoff
PROMPT 2. Failed SELECT on BENHNHAN
PROMPT 3. Failed DML on HSBA_DV
PROMPT 4. UPDATE on HSBA
PROMPT 5. DML on DONTHUOC + VPD function execution
