SET SERVEROUTPUT ON;
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

PROMPT === Requirement 1 / RBAC setup ===

BEGIN EXECUTE IMMEDIATE 'DROP VIEW V_SELF_NHANVIEN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW V_SELF_BENHNHAN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW V_TECHNICIAN_HSBA_DV'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW V_PATIENT_HSBA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW V_PATIENT_DONTHUOC'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_HSBADV_TECH_ONLY'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
    FOR r IN (
        SELECT role
        FROM dba_roles
        WHERE role IN ('DIEU_PHOI_VIEN', 'BAC_SI_Y_SI', 'KY_THUAT_VIEN', 'BENH_NHAN')
    ) LOOP
        EXECUTE IMMEDIATE 'DROP ROLE ' || r.role;
    END LOOP;
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

CREATE ROLE DIEU_PHOI_VIEN;
CREATE ROLE BAC_SI_Y_SI;
CREATE ROLE KY_THUAT_VIEN;
CREATE ROLE BENH_NHAN;

CREATE OR REPLACE VIEW V_SELF_NHANVIEN AS
SELECT MANV, HOTEN, PHAI, NGAYSINH, CMND, QUEQUAN, SODT, VAITRO, CHUYENKHOA, USERNAME
FROM NHANVIEN
WHERE UPPER(USERNAME) = UPPER(SYS_CONTEXT('USERENV', 'SESSION_USER'));

CREATE OR REPLACE VIEW V_SELF_BENHNHAN AS
SELECT MABN, TENBN, PHAI, NGAYSINH, CCCD, SONHA, TENDUONG, QUANHUYEN,
       TINHTP, TIENSUBENH, TIENSUBENHGD, DIUNGTHUOC, USERNAME
FROM BENHNHAN
WHERE UPPER(USERNAME) = UPPER(SYS_CONTEXT('USERENV', 'SESSION_USER'));

CREATE OR REPLACE VIEW V_TECHNICIAN_HSBA_DV AS
SELECT d.MAHSBA, d.LOAIDV, d.NGAYDV, d.KETQUA, d.MAKTV
FROM HSBA_DV d
WHERE d.MAKTV = (
    SELECT n.MANV
    FROM NHANVIEN n
    WHERE UPPER(n.USERNAME) = UPPER(SYS_CONTEXT('USERENV', 'SESSION_USER'))
);

CREATE OR REPLACE VIEW V_PATIENT_HSBA AS
SELECT h.MAHSBA, h.MABN, h.NGAY, h.CHANDOAN, h.DIEUTRI, h.MABS, h.MAKHOA, h.KETLUAN
FROM HSBA h
WHERE h.MABN = (
    SELECT b.MABN
    FROM BENHNHAN b
    WHERE UPPER(b.USERNAME) = UPPER(SYS_CONTEXT('USERENV', 'SESSION_USER'))
);

CREATE OR REPLACE VIEW V_PATIENT_DONTHUOC AS
SELECT d.MAHSBA, d.NGAYDT, d.TENTHUOC, d.LIEUDUNG
FROM DONTHUOC d
JOIN HSBA h ON h.MAHSBA = d.MAHSBA
WHERE h.MABN = (
    SELECT b.MABN
    FROM BENHNHAN b
    WHERE UPPER(b.USERNAME) = UPPER(SYS_CONTEXT('USERENV', 'SESSION_USER'))
);

CREATE OR REPLACE TRIGGER TRG_HSBADV_TECH_ONLY
BEFORE UPDATE OF KETQUA ON HSBA_DV
FOR EACH ROW
DECLARE
    v_manv NHANVIEN.MANV%TYPE;
BEGIN
    SELECT MANV
    INTO v_manv
    FROM NHANVIEN
    WHERE UPPER(USERNAME) = UPPER(SYS_CONTEXT('USERENV', 'SESSION_USER'));

    IF :OLD.MAKTV != v_manv THEN
        RAISE_APPLICATION_ERROR(-20010, 'Technician can update only assigned HSBA_DV rows.');
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20011, 'Current Oracle user is not mapped to a technician row.');
END;
/

GRANT SELECT, INSERT, UPDATE ON BENHNHAN TO DIEU_PHOI_VIEN;
GRANT SELECT, INSERT ON HSBA TO DIEU_PHOI_VIEN;
GRANT UPDATE (MABS, MAKHOA) ON HSBA TO DIEU_PHOI_VIEN;
GRANT SELECT ON NHANVIEN TO DIEU_PHOI_VIEN;
GRANT SELECT, INSERT ON HSBA_DV TO DIEU_PHOI_VIEN;
GRANT UPDATE (MAKTV) ON HSBA_DV TO DIEU_PHOI_VIEN;

GRANT SELECT ON HSBA TO BAC_SI_Y_SI;
GRANT SELECT ON BENHNHAN TO BAC_SI_Y_SI;
GRANT UPDATE (CHANDOAN, DIEUTRI, KETLUAN) ON HSBA TO BAC_SI_Y_SI;
GRANT UPDATE (TIENSUBENH, TIENSUBENHGD, DIUNGTHUOC) ON BENHNHAN TO BAC_SI_Y_SI;
GRANT INSERT, DELETE ON HSBA_DV TO BAC_SI_Y_SI;
GRANT INSERT, UPDATE, DELETE ON DONTHUOC TO BAC_SI_Y_SI;

GRANT SELECT ON V_TECHNICIAN_HSBA_DV TO KY_THUAT_VIEN;
GRANT UPDATE (KETQUA) ON HSBA_DV TO KY_THUAT_VIEN;
GRANT SELECT ON V_SELF_NHANVIEN TO KY_THUAT_VIEN;
GRANT UPDATE (QUEQUAN, SODT) ON V_SELF_NHANVIEN TO KY_THUAT_VIEN;

GRANT SELECT ON V_SELF_BENHNHAN TO BENH_NHAN;
GRANT UPDATE (SONHA, TENDUONG, QUANHUYEN, TINHTP, TIENSUBENH, TIENSUBENHGD, DIUNGTHUOC) ON V_SELF_BENHNHAN TO BENH_NHAN;
GRANT SELECT ON V_PATIENT_HSBA TO BENH_NHAN;
GRANT SELECT ON V_PATIENT_DONTHUOC TO BENH_NHAN;

GRANT SELECT ON V_SELF_NHANVIEN TO DIEU_PHOI_VIEN;
GRANT UPDATE (QUEQUAN, SODT) ON V_SELF_NHANVIEN TO DIEU_PHOI_VIEN;
GRANT SELECT ON V_SELF_NHANVIEN TO BAC_SI_Y_SI;
GRANT UPDATE (QUEQUAN, SODT) ON V_SELF_NHANVIEN TO BAC_SI_Y_SI;

DECLARE
    CURSOR staff_cursor IS
        SELECT USERNAME,
               CASE
                   WHEN VAITRO = N'Điều phối viên' THEN 'DIEU_PHOI_VIEN'
                   WHEN VAITRO = N'Bác sĩ/Y sĩ' THEN 'BAC_SI_Y_SI'
                   WHEN VAITRO = N'Kỹ thuật viên' THEN 'KY_THUAT_VIEN'
               END AS ROLE_NAME
        FROM NHANVIEN
        WHERE USERNAME IS NOT NULL;

    CURSOR patient_cursor IS
        SELECT USERNAME
        FROM BENHNHAN
        WHERE USERNAME IS NOT NULL;
BEGIN
    FOR r IN staff_cursor LOOP
        BEGIN
            EXECUTE IMMEDIATE 'CREATE USER ' || r.USERNAME || ' IDENTIFIED BY "123"';
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -1920 THEN
                    RAISE;
                END IF;
        END;

        EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO ' || r.USERNAME;
        IF r.ROLE_NAME IS NOT NULL THEN
            EXECUTE IMMEDIATE 'GRANT ' || r.ROLE_NAME || ' TO ' || r.USERNAME;
        END IF;
    END LOOP;

    FOR r IN patient_cursor LOOP
        BEGIN
            EXECUTE IMMEDIATE 'CREATE USER ' || r.USERNAME || ' IDENTIFIED BY "123"';
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -1920 THEN
                    RAISE;
                END IF;
        END;

        EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO ' || r.USERNAME;
        EXECUTE IMMEDIATE 'GRANT BENH_NHAN TO ' || r.USERNAME;
    END LOOP;
END;
/

COMMIT;

PROMPT === RBAC setup completed ===
