SET SERVEROUTPUT ON;

PROMPT === Requirement 2 / OLS setup ===

BEGIN
    SA_SYSDBA.DISABLE_POLICY(policy_name => 'THONGBAO_OLS');
    SA_SYSDBA.DROP_POLICY(policy_name => 'THONGBAO_OLS', drop_column => FALSE);
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    SA_SYSDBA.CREATE_POLICY(
        policy_name      => 'THONGBAO_OLS',
        column_name      => 'OLS_LABEL',
        default_options  => 'READ_CONTROL'
    );

    SA_COMPONENTS.CREATE_LEVEL('THONGBAO_OLS', 30, 'L3_GD', 'Ban Giam Doc');
    SA_COMPONENTS.CREATE_LEVEL('THONGBAO_OLS', 20, 'L2_LD', 'Lanh Dao Khoa');
    SA_COMPONENTS.CREATE_LEVEL('THONGBAO_OLS', 10, 'L1_NV', 'Nhan Vien');

    SA_COMPONENTS.CREATE_COMPARTMENT('THONGBAO_OLS', 100, 'C_TIEU', 'Tieu Hoa');
    SA_COMPONENTS.CREATE_COMPARTMENT('THONGBAO_OLS', 110, 'C_THAN', 'Than Kinh');
    SA_COMPONENTS.CREATE_COMPARTMENT('THONGBAO_OLS', 120, 'C_TIM',  'Tim Mach');

    SA_COMPONENTS.CREATE_GROUP('THONGBAO_OLS', 10, 'G_HN',  'Ha Noi');
    SA_COMPONENTS.CREATE_GROUP('THONGBAO_OLS', 20, 'G_HP',  'Hai Phong');
    SA_COMPONENTS.CREATE_GROUP('THONGBAO_OLS', 30, 'G_HCM', 'Ho Chi Minh');
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_OLS', 1000, 'L1_NV');
    SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_OLS', 2000, 'L2_LD');
    SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_OLS', 3000, 'L3_GD');
    SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_OLS', 2100, 'L2_LD:C_TIEU');
    SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_OLS', 1130, 'L1_NV:C_TIEU:G_HCM');
    SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_OLS', 1110, 'L1_NV:C_TIEU:G_HN');
    SA_LABEL_ADMIN.CREATE_LABEL('THONGBAO_OLS', 2220, 'L2_LD:C_TIEU,C_THAN:G_HP');
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    SA_POLICY_ADMIN.APPLY_TABLE_POLICY(
        policy_name   => 'THONGBAO_OLS',
        schema_name   => USER,
        table_name    => 'THONGBAO',
        table_options => 'READ_CONTROL'
    );
END;
/

UPDATE THONGBAO
SET OLS_LABEL = CHAR_TO_LABEL('THONGBAO_OLS', 'L1_NV')
WHERE OLS_LABEL IS NULL;

DELETE FROM THONGBAO
WHERE NOIDUNG LIKE 't1:%'
   OR NOIDUNG LIKE 't2:%'
   OR NOIDUNG LIKE 't3:%'
   OR NOIDUNG LIKE 't4:%'
   OR NOIDUNG LIKE 't5:%'
   OR NOIDUNG LIKE 't6:%'
   OR NOIDUNG LIKE 't7:%';

INSERT INTO THONGBAO (NOIDUNG, NGAYGIO, DIADIEM, OLS_LABEL)
VALUES ('t1: Gui den toan bo nhan vien', SYSTIMESTAMP, 'Online', CHAR_TO_LABEL('THONGBAO_OLS', 'L1_NV'));

INSERT INTO THONGBAO (NOIDUNG, NGAYGIO, DIADIEM, OLS_LABEL)
VALUES ('t2: Gui den toan bo Ban giam doc', SYSTIMESTAMP, 'Phong hop Giam doc', CHAR_TO_LABEL('THONGBAO_OLS', 'L3_GD'));

INSERT INTO THONGBAO (NOIDUNG, NGAYGIO, DIADIEM, OLS_LABEL)
VALUES ('t3: Gui den cac lanh dao khoa', SYSTIMESTAMP, 'Hoi truong', CHAR_TO_LABEL('THONGBAO_OLS', 'L2_LD'));

INSERT INTO THONGBAO (NOIDUNG, NGAYGIO, DIADIEM, OLS_LABEL)
VALUES ('t4: Gui den lanh dao Khoa tieu hoa', SYSTIMESTAMP, 'Khoa tieu hoa', CHAR_TO_LABEL('THONGBAO_OLS', 'L2_LD:C_TIEU'));

INSERT INTO THONGBAO (NOIDUNG, NGAYGIO, DIADIEM, OLS_LABEL)
VALUES ('t5: Gui den nhan vien Khoa tieu hoa o Ho Chi Minh', SYSTIMESTAMP, 'Ho Chi Minh', CHAR_TO_LABEL('THONGBAO_OLS', 'L1_NV:C_TIEU:G_HCM'));

INSERT INTO THONGBAO (NOIDUNG, NGAYGIO, DIADIEM, OLS_LABEL)
VALUES ('t6: Gui den nhan vien Khoa tieu hoa o Ha Noi', SYSTIMESTAMP, 'Ha Noi', CHAR_TO_LABEL('THONGBAO_OLS', 'L1_NV:C_TIEU:G_HN'));

INSERT INTO THONGBAO (NOIDUNG, NGAYGIO, DIADIEM, OLS_LABEL)
VALUES ('t7: Gui den lanh dao Khoa tieu hoa va Khoa than kinh tai Hai Phong', SYSTIMESTAMP, 'Hai Phong', CHAR_TO_LABEL('THONGBAO_OLS', 'L2_LD:C_TIEU,C_THAN:G_HP'));

BEGIN
    SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_OLS', 'NV000001', 'L3_GD:C_TIEU,C_THAN,C_TIM:G_HN,G_HP,G_HCM');
    SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_OLS', 'NV000090', 'L2_LD:C_TIM:G_HCM');
    SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_OLS', 'NV000060', 'L2_LD:C_THAN:G_HN');
    SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_OLS', 'NV000061', 'L1_NV:C_THAN:G_HCM');
    SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_OLS', 'NV000091', 'L1_NV:C_TIM:G_HCM');
    SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_OLS', 'NV000002', 'L2_LD:C_TIM:G_HCM');
    SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_OLS', 'NV000003', 'L2_LD:C_TIEU,C_THAN,C_TIM:G_HN,G_HP,G_HCM');
    SA_USER_ADMIN.SET_USER_LABELS('THONGBAO_OLS', 'NV000030', 'L1_NV:C_TIEU:G_HN');
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

GRANT SELECT ON THONGBAO TO DIEU_PHOI_VIEN;
GRANT SELECT ON THONGBAO TO BAC_SI_Y_SI;
GRANT SELECT ON THONGBAO TO KY_THUAT_VIEN;
GRANT SELECT ON THONGBAO TO BENH_NHAN;

COMMIT;

PROMPT === OLS setup completed ===
